# Generated by Django 3.2.5 on 2021-08-05 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_follow_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
