version: '3.3'
services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  frontend:
    image: dvoryanoff/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  backend:
    image: dvoryanoff/foodgram_backend:latest
    restart: always
    depends_on:
      - db
    volumes:
      - static_value:/code/backend_static/
      - media_value:/code/backend_media/
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - static_value:/code/backend_static/
      - media_value:/code/backend_media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
    restart: always
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  static_value:
  media_value: