# Generated by Django 3.2.5 on 2021-08-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Укажите Время приготовления в минутах', verbose_name='Время приготовления в минутах'),
        ),
    ]
