# Generated by Django 3.2.5 on 2021-08-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-id'], 'verbose_name': ('Избранное',), 'verbose_name_plural': 'Избранные'},
        ),
    ]
