# Generated by Django 3.2.5 on 2021-08-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_ingredient_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Укажите название тега', max_length=200, verbose_name='Название тега'),
        ),
    ]
